export const API_DOMAIN = 'https://flowerdelivery5.herokuapp.com';

// AUTH CONSTANTS
export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const ORDER_STARTED = 'ORDER_STARTED'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILED = 'ORDER_FAILED'
export const GET_ORDERS = 'GET_ORDERS'

export const SEARCH_ORDERS = 'SEARCH_ORDERS'

