export const API_DOMAIN = 'https://flowerdelivery5.herokuapp.com';
// export const API_DOMAIN = 'https://my-json-server.typicode.com/typicode/demo/';
export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ORDER_STARTED = 'ORDER_STARTED'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILED = 'ORDER_FAILED'
export const SEARCH_ORDERS = 'SEARCH_ORDERS'

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const EMPLOYER_REQUEST = 'EMPLOYER_REQUEST';
export const EMPLOYER_SUCCESS = 'EMPLOYER_SUCCESS';
export const EMPLOYER_FAILURE = 'EMPLOYER_FAILURE';

export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE';
