export const SIGNIN_STARTED = 'SIGNIN_STARTED'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_ROLE = 'SET_ROLE'

export const ORDER_STARTED = 'ORDER_STARTED'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILED = 'ORDER_FAILED'
export const GET_ORDERS = 'GET_ORDERS'

export const SEARCH_ORDERS = 'SEARCH_ORDERS'
